name: Deploy Twitter Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  

    - name: Deploy to Oracle VM
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.ORACLE_HOST }}  
        username: ${{ secrets.ORACLE_USER }}  
        key: ${{ secrets.ORACLE_SSH_KEY }}  
        script: |
            echo "Setting up SSH config:"
            echo -e "Host github.com\n\tHostName github.com\n\tIdentityFile /home/ubuntu/.ssh/temp_ssh/id_ed25519\n\tIdentitiesOnly yes" > /home/ubuntu/.ssh/config
            chmod 600 /home/ubuntu/.ssh/config
            echo "Pulling latest code:"
            GIT_SSH_COMMAND="ssh -i /home/ubuntu/.ssh/temp_ssh/id_ed25519 -o IdentitiesOnly=yes" git pull origin main || echo "Git pull failed"
            echo "Activating virtual environment:"
            source venv/bin/activate
            echo "Restarting bot:"
            screen -ls | grep "phil_bot" && screen -S phil_bot -X quit || true
            screen -dmS phil_bot venv/bin/python3 xtwitter_bot.py > bot.log 2>&1
            echo "Active screen sessions:"
            screen -ls