name: Deploy Twitter Bot

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  

    - name: Deploy to Oracle VM
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.ORACLE_HOST }}  
        username: ${{ secrets.ORACLE_USER }}  
        key: ${{ secrets.ORACLE_SSH_KEY }}  
        script: |
          cd /home/ubuntu/xtwitter_bot  
          git pull origin main  
          source venv/bin/activate
          screen -ls | grep "phil_bot" && screen -S phil_bot -X quit || true
          screen -dmS phil_bot venv/bin/python3 xtwitter_bot.py > bot.log 2>&1
          screen -ls  
